const students = [
    {
      number: 1,
      name: "Ravi ",
      ticket:1,
      rating:3,
      exam:5,
      more:'More Details',
      fullname:'Ravi Pandey',
      contact:'+91 8210506008',
      email:'ravipandey5146@gmail.com',
      address:'Bihar',
      field:'Machine Learning'

      },

    {
        number: 2,
        name: "Rohit",
        ticket:2,
        rating:2,
        exam:4,
        more:'More Details',
        fullname:'Rohit singh',
        contact:'+91 6274005678',
        email:'rohitsingh@gmail.com',
        address:'Uttar Pradesh',
        field:'Cyber Security'
    },
    {
        number: 3,
        name: "Anand ",
        ticket:3,
        rating:5,
        exam:4,
        more:'More Details',
        fullname:'Anand Gupta',
        contact:'+91 9874522117',
        email:'anand22113@gmail.com',
        address:'Uttar Pradesh',
        field:'Machine Learning'
    },
    {
        number: 4,
        name: "Arjun",
        ticket:4,
        rating:2,
        exam:1,
        more:'More Details',
        fullname:'Arjun',
        contact:'+91 7287962265',
        email:'arjunchauhan@gmail.com',
        address:'Uttar Pradesh',
        field:'cyber Security '
    },
    {
        number: 5,
        name: "Ayush Ranjan",
        ticket:5,
        rating:0,
        exam:3,
        more:'More Details',
        fullname:'Ayush Singh Ranjan Rajput',
        contact:'+91 9866955023',
        email:'ayushsinghranjan@gmail.com',
        address:'Bihar',
        field:'Computer Science Engineering'
    },
    {
        number: 6,
        name: "Raj",
        ticket:6,
        rating:4,
        exam:3,
        more:'More Details',
        fullname:'Raj mishra ',
        contact:'+91 6281862555',
        email:'rajmishra@gmail.com',
        address:'Gujarat',
        field:'Mechanical Engineering'
    },
    {
        number: 7,
        name: "Sani ",
        ticket:7,
        rating:3,
        exam:1,
        more:'More Details',
        fullname:'Sani Sharma',
        contact:'+91 9584477552',
        email:'sani2001@gmail.com',
        address:'Uttar Pradesh',
        field:'Machine Learning'
    },
    {
        number: 8,
        name: "vivek",
        ticket:8,
        rating:2,
        exam:2,
        more:'More Details',
        fullname:'vivek',
        contact:'+91 9996699658',
        email:'vivekshahu@gmail.com',
        address:'Kolkata',
        field:'Web Development'
    },
    {
        number: 9,
        name: "Sachin ",
        ticket:9,
        rating:0,
        exam:2,
        more:'More Details',
        fullname:'Sachin Jha ',
        contact:'+91 7032587999',
        email:'sachinjha674@gmail.com',
        address:'Banaras',
        field:'Computer Science'
    },
    {
        number: 10,
        name: "Satya",
        ticket:10,
        rating:2,
        exam:3,
        more:'More Details',
        fullname:'Naga Samudram Satya',
        contact:'+91 9849245228',
        email:'satyanl124@gmail.com',
        address:'Andhra Pradesh',
        field:'Front-End Engineer'
    },
    {
        number: 11,
        name: "Akash",
        ticket:11,
        rating:2,
        exam:2,
        more:'More Details',
        fullname:'Lalith Sai Akash',
        contact:'+91 9866955023',
        email:'klsakash143@gmail.com',
        address:'VishakhaPatnam',
        field:'Software-Developer'
    },
    {
        number: 12,
        name: "Prabhas",
        ticket:12,
        rating:5,
        exam:5,
        more:'More Details',
      fullname:'Uppalapaati Prabhas Varma',
      contact:'+91 9999999998',
      email:'psvarmadarling143@gmail.com',
      address:'Andhra Pradesh',
      field:'Acting'
    },
    {
        number: 13,
        name: "Jasmeet",
        ticket:13,
        rating:2,
        exam:1,
        more:'More Details',
      fullname:'Jasmeet Astwal',
      contact:'+91 6281587562',
      email:'jastwal549@gmail.com',
      address:'Punjab',
      field:'Bussiness Management'
    },
    {
        number: 14,
        name: "Ganesh",
        ticket:14,
        rating:0,
        exam:4,
        more:'More Details',
      fullname:'Alla Ganesh',
      contact:'+91 9587452115',
      email:'aganna143@gmail.com',
      address:'Andhra Pradesh',
      field:'Bussiness Management'
    },
    {
        number: 15,
        name: "Marcus",
        ticket:15,
        rating:0,
        exam:0,
        more:'More Details',
      fullname:'Marcus Lucifer',
      contact:'+91 6000000000',
      email:'mlucifer435@gmail.com',
      address:'Chennai',
      field:'Actor'
    },
    {
        number: 16,
        name: "John",
        ticket:16,
        rating:5,
        exam:0,
        more:'More Details',
      fullname:'John Abraham',
      contact:'+91 6281666666',
      email:'jabraham1853@gmail.com',
      address:'Assam',
      field:'Political Science'
    },
    {
        number: 17,
        name: "Kalyan",
        ticket:17,
        rating:2,
        exam:3,
        more:'More Details',
      fullname:'Kalyan Ram',
      contact:'+91 6281500000',
      email:'nkalyanram0073@gmail.com',
      address:'Andhra Pradesh',
      field:'Acting'
    },
    {
        number: 18,
        name: "Tarak",
        ticket:18,
        rating:4,
        exam:4,
        more:'More Details',
      fullname:'Tarak Reddy',
      contact:'+91 9999547885',
      email:'itarak1000@gmail.com',
      address:'Gujarat',
      field:'Electrical Engineering'
    },
    {
        number: 19,
        name: "Prasanth",
        ticket:19,
        rating:0,
        exam:0,
        more:'More Details',
      fullname:'Siva Prasanth',
      contact:'+91 8888887885',
      email:'kjsprasanth1073@gmail.com',
      address:'Jammu and Kashmir',
      field:'Civil Engineering'
    },
    {
        number: 20,
        name: "Ashok Reddy",
        ticket:20,
        rating:2,
        exam:4,
        more:'More Details',
      fullname:'Ashok Reddy Yerrasaani',
      contact:'+91 6281525247',
      email:'yashokred340@gmail.com',
      address:'Andhra Pradesh',
      field:'Admin Officer'
    },
    {
        number: 21,
        name: "Ajay",
        ticket:21,
        rating:0,
        exam:4,
        more:'More Details',
      fullname:'Ajay Gowd',
      contact:'+91 8881547885',
      email:'gowdajay786@gmail.com',
      address:'Uttar Pradesh',
      field:'Mechanical Engineering'
    },
    {
        number: 22,
        name: "Sri Ram",
        ticket:22,
        rating:2,
        exam:3,
        more:'More Details',
      fullname:'Sri Ram Sarma',
      contact:'+91 6281747885',
      email:'sriramsarma1873@gmail.com',
      address:'Andhra Pradesh',
      field:'Cyber Security'
    },
    {
        number: 23,
        name: "Rama Raju",
        ticket:23,
        rating:2,
        exam:1,
        more:'More Details',
      fullname:'Chekuri Rama Raju',
      contact:'+91 6281000885',
      email:'chrraju1873@gmail.com',
      address:'Andhra Pradesh',
      field:'Political Science'
    },
    {
        number: 24,
        name: "Pulkeet",
        ticket:24,
        rating:2,
        exam:4,
        more:'More Details',
      fullname:'pulkeet Das',
      contact:'+91 62878547885',
      email:'pulkeetdas@gmail.com',
      address:'West Bengal',
      field:'Front-End Engineer'
    },
    {
        number: 25,
        name: "Rocky ",
        ticket:25,
        rating:2,
        exam:0,
        more:'More Details',
      fullname:'Rocky Verma',
      contact:'+91 6784547885',
      email:'Rockyverma876@gmail.com',
      address:'Punjab',
      field:'Software Testing'
    }

  ];
  students.forEach((student) => {
    const overallGrade = student.rating + student.exam;
    student.overallGrade = overallGrade;
    student.status = overallGrade >= 4.0 ? "pass" : "fail";
  });
  export default students;